# -*- coding: UTF-8 -*-

class AnalV100():

    def __init__(self):
        self.doc_type = 'ANA'
        self.version = '1.00'
        self.doc_format_dict = {
            'author_name':{
                'xlsname':'担当者',
                'xlspos':[(1,5)],
                'datatype' : 'STR',
                'needcheck' : True,
            },
            'definition_id':{
                'xlsname':'TAGL要件定義ID',
                'xlspos':[(2,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'unique_id':{
                 'xlsname': 'ユニークID',
                'xlspos': [(3,5)],
                'datatype': 'INT',
                'needcheck' : True,
            },
            'major_category':{
                'xlsname': '大分類',
                'xlspos': [(4,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'medium_category':{
                'xlsname': '中分類',
                'xlspos': [(5,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'small_category':{
                'xlsname': '小分類',
                'xlspos': [(6,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'detail':{
                'xlsname': '詳細',
                'xlspos': [(7, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'basic_req':{
                'xlsname': '基本要件',
                'xlspos': [(8, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'rel_requirement':{
                'xlsname': '関連基本要件',
                'xlspos': [(9, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'exception':{
                'xlsname': '除外',
                'xlspos': [(10, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'dcu_meu':{
                'xlsname': 'TAGL-PF->DCU/MEUどちらの要件か',
                'xlspos': [(11, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_status':{
                'xlsname': 'TAGL-PF->状態',
                'xlspos': [(12, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_trigger':{
                'xlsname': 'TAGL-PF->トリガー',
                'xlspos': [(13, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_action':{
                'xlsname': 'TAGL-PF->動作',
                'xlspos': [(14, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'seq_diagram':{
                'xlsname': 'シーケンス図',
                'xlspos': [(15, 1)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'model_application':{
                'xlsname': '責務分担->アプリケーション',
                'xlspos': [(16, 2)],
                'datatype': 'STR',
                'model_id': 1,
                'needcheck' : True,
            },
            'model_kernel':{
                'xlsname': '責務分担->kernel',
                'xlspos': [(17, 2)],
                'datatype': 'STR',
                'model_id': 2,
                'needcheck' : True,
            },
            'model_systemd':{
                'xlsname': '責務分担->systemd',
                'xlspos': [(18, 2)],
                'datatype': 'STR',
                'model_id': 3,
                'needcheck' : True,
            },
            'model_system_manager':{
                'xlsname': 'BaseSystem->System Service->system_manager',
                'xlspos': [(19, 4)],
                'datatype': 'STR',
                'model_id': 4,
                'needcheck' : True,
            },
            'model_device_detection_service':{
                'xlsname': 'BaseSystem->System Service->device_detection_service',
                'xlspos': [(20, 4)],
                'datatype': 'STR',
                'model_id': 5,
                'needcheck' : True,
            },
            'model_window_system':{
                'xlsname': 'BaseSystem->System Service->window_system',
                'xlspos': [(21, 4)],
                'datatype': 'STR',
                'model_id': 6,
                'needcheck' : True,
            },
            'model_logger_service':{
                'xlsname': 'BaseSystem->System Service->logger_service',
                'xlspos': [(22, 4)],
                'datatype': 'STR',
                'model_id': 7,
                'needcheck' : True,
            },
            'model_resource_manager':{
                'xlsname': 'BaseSystem->System Service->resource_manager',
                'xlspos': [(23, 4)],
                'datatype': 'STR',
                'model_id': 8,
                'needcheck' : True,
            },
            'model_task_manager':{
                'xlsname': 'BaseSystem->System Service->task_manager',
                'xlspos': [(24, 4)],
                'datatype': 'STR',
                'model_id': 9,
                'needcheck' : True,
            },
            'model_update_service':{
                'xlsname': 'BaseSystem->System Service->update_service',
                'xlspos': [(25, 4)],
                'datatype': 'STR',
                'model_id': 10,
                'needcheck' : True,
            },
            'model_font':{
                'xlsname': 'BaseSystem->System Service->font',
                'xlspos': [(26, 4)],
                'datatype': 'STR',
                'model_id': 11,
                'needcheck' : True,
            },
            'model_mounter':{
                'xlsname': 'BaseSystem->System Service->mounter',
                'xlspos': [(27, 4)],
                'datatype': 'STR',
                'model_id': 12,
                'needcheck' : True,
            },
            'model_power_service':{
                'xlsname': 'BaseSystem->System Service->power_service',
                'xlspos': [(28, 4)],
                'datatype': 'STR',
                'model_id': 13,
                'needcheck' : True,
            },
            'model_version_library':{
                'xlsname': 'BaseSystem->System Service->version_library',
                'xlspos': [(29, 4)],
                'datatype': 'STR',
                'model_id': 14,
                'needcheck' : True,
            },
            'model_rom_access_library':{
                'xlsname': 'BaseSystem->System Service->rom_access_library',
                'xlspos': [(30, 4)],
                'datatype': 'STR',
                'model_id': 15,
                'needcheck' : True,
            },
            'model_interface_unified':{
                'xlsname': 'BaseSystem->System Service->interface_unified',
                'xlspos': [(31, 4)],
                'datatype': 'STR',
                'model_id': 16,
                'needcheck' : True,
            },
            'model_config':{
                'xlsname': 'BaseSystem->System Service->config',
                'xlspos': [(32, 4)],
                'datatype': 'STR',
                'model_id': 17,
                'needcheck' : True,
            },
            'model_notification_persistent_service':{
                'xlsname': 'BaseSystem->Native Service->notification_persistent_service',
                'xlspos': [(33, 4)],
                'datatype': 'STR',
                'model_id': 18,
                'needcheck' : True,
            },
            'model_image_storage_library':{
                'xlsname': 'BaseSystem->Native Service->image_storage_library',
                'xlspos': [(34, 4)],
                'datatype': 'STR',
                'model_id': 19,
                'needcheck' : True,
            },
            'model_framework_unified':{
                'xlsname': 'BaseSystem->Native Service->framework_unified',
                'xlspos': [(35, 4)],
                'datatype': 'STR',
                'model_id': 20,
                'needcheck' : True,
            },
            'model_backup_manager':{
                'xlsname': 'BaseSystem->Native Service->backup_manager',
                'xlspos': [(36, 4)],
                'datatype': 'STR',
                'model_id': 21,
                'needcheck' : True,
            },
            'model_memory_gpio_access_library':{
                'xlsname': 'BaseSystem->Native Service->memory_gpio_access_library',
                'xlspos': [(37, 4)],
                'datatype': 'STR',
                'model_id': 22,
                'needcheck' : True,
            },
            'model_common_library':{
                'xlsname': 'BaseSystem->Native Service->common_library',
                'xlspos': [(38, 4)],
                'datatype': 'STR',
                'model_id': 23,
                'needcheck' : True,
            },
            'model_lock_manager':{
                'xlsname': 'BaseSystem->Native Service->lock_manager',
                'xlspos': [(39, 4)],
                'datatype': 'STR',
                'model_id': 24,
                'needcheck' : True,
            },
            'model_webdav_manager':{
                'xlsname': 'BaseSystem->Native Service->webdav_manager',
                'xlspos': [(40, 4)],
                'datatype': 'STR',
                'model_id': 25,
                'needcheck' : True,
            },
            'model_paslog_library':{
                'xlsname': 'BaseSystem->Native Service->paslog_library',
                'xlspos': [(41, 4)],
                'datatype': 'STR',
                'model_id': 26,
                'needcheck' : True,
            },
            'model_analysis_library':{
                'xlsname': 'BaseSystem->Native Service->analysis_library',
                'xlspos': [(42, 4)],
                'datatype': 'STR',
                'model_id': 27,
                'needcheck' : True,
            },
            'model_storage_library':{
                'xlsname': 'BaseSystem->Native Service->storage_library',
                'xlspos': [(43, 4)],
                'datatype': 'STR',
                'model_id': 28,
                'needcheck' : True,
            },
            'model_communication_utility_library':{
                'xlsname': 'BaseSystem->Native Service->communication_utility_library',
                'xlspos': [(44, 4)],
                'datatype': 'STR',
                'model_id': 29,
                'needcheck' : True,
            },
            'model_communication':{
                'xlsname': 'BaseSystem->Peripheral Services->communication',
                'xlspos': [(45, 4)],
                'datatype': 'STR',
                'model_id': 30,
                'needcheck' : True,
            },
            'model_communication_usb':{
                'xlsname': 'BaseSystem->Peripheral Services->communication_usb',
                'xlspos': [(46, 4)],
                'datatype': 'STR',
                'model_id': 31,
                'needcheck' : True,
            },
            'model_communication_sh4':{
                'xlsname': 'BaseSystem->Peripheral Services->communication_sh4',
                'xlspos': [(47, 4)],
                'datatype': 'STR',
                'model_id': 32,
                'needcheck' : True,
            },
            'model_power_supply_manager_shadow':{
                'xlsname': 'BaseSystem->Peripheral Services->power_supply_manager_shadow',
                'xlspos': [(48, 4)],
                'datatype': 'STR',
                'model_id': 33,
                'needcheck' : True,
            },
            'model_lanserver':{
                'xlsname': 'BaseSystem->Peripheral Services->lanserver',
                'xlspos': [(49, 4)],
                'datatype': 'STR',
                'model_id': 34,
                'needcheck' : True,
            },
            'model_model_switchhandler':{
                'xlsname': 'BaseSystem->Peripheral Services->switchhandler',
                'xlspos': [(50, 4)],
                'datatype': 'STR',
                'model_id': 35,
                'needcheck' : True,
            },
            'model_cangw_master':{
                'xlsname': 'BaseSystem->Peripheral Services->cangw_master',
                'xlspos': [(51, 4)],
                'datatype': 'STR',
                'model_id': 36,
                'needcheck' : True,
            },
            'model_cangw_slave':{
                'xlsname': 'BaseSystem->Peripheral Services->cangw_slave',
                'xlspos': [(52, 4)],
                'datatype': 'STR',
                'model_id': 37,
                'needcheck' : True,
            },
            'model_external_unit_auth':{
                'xlsname': 'BaseSystem->Peripheral Services->external_unit_auth',
                'xlspos': [(53, 4)],
                'datatype': 'STR',
                'model_id': 38,
                'needcheck' : True,
            },
            'model_proxyservice':{
                'xlsname': 'BaseSystem->Peripheral Services->proxyservice',
                'xlspos': [(54, 4)],
                'datatype': 'STR',
                'model_id': 39,
                'needcheck' : True,
            },
            'model_mostshadow':{
                'xlsname': 'BaseSystem->Peripheral Services->mostshadow',
                'xlspos': [(55, 4)],
                'datatype': 'STR',
                'model_id': 40,
                'needcheck' : True,
            },
            'model_clock':{
                'xlsname': 'BaseSystem->Vehicle Services->clock',
                'xlspos': [(56, 4)],
                'datatype': 'STR',
                'model_id': 41,
                'needcheck' : True,
            },
            'model_vehicle':{
                'xlsname': 'BaseSystem->Vehicle Services->vehicle',
                'xlspos': [(57, 4)],
                'datatype': 'STR',
                'model_id': 42,
                'needcheck' : True,
            },
            'model_diag_code':{
                'xlsname': 'BaseSystem->Vehicle Services->diag_code',
                'xlspos': [(58, 4)],
                'datatype': 'STR',
                'model_id': 43,
                'needcheck' : True,
            },
            'model_diag_record':{
                'xlsname': 'BaseSystem->Vehicle Services->diag_record',
                'xlspos': [(59, 4)],
                'datatype': 'STR',
                'model_id': 44,
                'needcheck' : True,
            },
            'model_positioning':{
                'xlsname': 'BaseSystem->Vehicle Services->positioning',
                'xlspos': [(60, 4)],
                'datatype': 'STR',
                'model_id': 45,
                'needcheck' : True,
            },
            'model_mic_service':{
                'xlsname': 'BaseSystem->Audio Service->mic_service',
                'xlspos': [(61, 4)],
                'datatype': 'STR',
                'model_id': 46,
                'needcheck' : True,
            },
            'model_sound_service':{
                'xlsname': 'BaseSystem->Audio Service->sound_service',
                'xlspos': [(62, 4)],
                'datatype': 'STR',
                'model_id': 47,
                'needcheck' : True,
            },
            'model_alsa':{
                'xlsname': 'BaseSystem->Audio Service->alsa',
                'xlspos': [(63, 4)],
                'datatype': 'STR',
                'model_id': 48,
                'needcheck' : True,
            },
            'model_asrc':{
                'xlsname': 'BaseSystem->Audio Service->asrc',
                'xlspos': [(64, 4)],
                'datatype': 'STR',
                'model_id': 49,
                'needcheck' : True,
            },
            'model_event_library':{
                'xlsname': 'BaseSystem->OtherServices->event_library',
                'xlspos': [(65, 4)],
                'datatype': 'STR',
                'model_id': 50,
                'needcheck' : True,
            },
            'model_rpc_library':{
                'xlsname': 'BaseSystem->OtherServices->rpc_library',
                'xlspos': [(66, 4)],
                'datatype': 'STR',
                'model_id': 51,
                'needcheck' : True,
            },
            'model_posix_based_os001_legacy_library':{
                'xlsname': 'BaseSystem->OtherServices->posix_based_os001_legacy_library',
                'xlspos': [(67, 4)],
                'datatype': 'STR',
                'model_id': 52,
                'needcheck' : True,
            },
            'model_startup_bgm':{
                'xlsname': 'BaseSystem->OtherServices->startup_bgm',
                'xlspos': [(68, 4)],
                'datatype': 'STR',
                'model_id': 53,
                'needcheck' : True,
            },
            'model_dummy_device_read':{
                'xlsname': 'BaseSystem->OtherServices->dummy_device_read',
                'xlspos': [(69, 4)],
                'datatype': 'STR',
                'model_id': 54,
                'needcheck' : True,
            },
            'model_vehicle_parameter_library':{
                'xlsname': 'BaseSystem->OtherServices->vehicle_parameter_library',
                'xlspos': [(70, 4)],
                'datatype': 'STR',
                'model_id': 55,
                'needcheck' : True,
            },
            'model_graphics_library':{
                'xlsname': 'BaseSystem->Graphics Service->graphics_library',
                'xlspos': [(71, 4)],
                'datatype': 'STR',
                'model_id': 56,
                'needcheck' : True,
            },
            'model_graphics_service':{
                'xlsname': 'BaseSystem->Graphics Service->graphics_service',
                'xlspos': [(72, 4)],
                'datatype': 'STR',
                'model_id': 57,
                'needcheck' : True,
            },
            'model_mode_manager':{
                'xlsname': 'BaseSystem->Applicatio Management->Mode Manager',
                'xlspos': [(73, 4)],
                'datatype': 'STR',
                'model_id': 58,
                'needcheck' : True,
            },
            'model_arbitration_manager':{
                'xlsname': 'BaseSystem->Applicatio Management->Arbitration Manager',
                'xlspos': [(74, 4)],
                'datatype': 'STR',
                'model_id': 59,
                'needcheck' : True,
            },
            'model_arbitration_service':{
                'xlsname': 'BaseSystem->Applicatio Management->Arbitration Service',
                'xlspos': [(75, 4)],
                'datatype': 'STR',
                'model_id': 60,
                'needcheck' : True,
            },
            'model_display_service':{
                'xlsname': 'BaseSystem->Applicatio Management->Display Service',
                'xlspos': [(76, 4)],
                'datatype': 'STR',
                'model_id': 61,
                'needcheck' : True,
            },
            'model_audio_manager':{
                'xlsname': 'BaseSystem->Applicatio Management->Audio Manager',
                'xlspos': [(77, 4)],
                'datatype': 'STR',
                'model_id': 62,
                'needcheck' : True,
            },
            'model_startup':{
                'xlsname': 'BaseSystem->Applicatio Management->Startup',
                'xlspos': [(78, 4)],
                'datatype': 'STR',
                'model_id': 63,
                'needcheck' : True,
            },
            'model_window_manager':{
                'xlsname': 'BaseSystem->Applicatio Management->Window Manager',
                'xlspos': [(79, 4)],
                'datatype': 'STR',
                'model_id': 64,
                'needcheck' : True,
            },
            'model_launch':{
                'xlsname': 'BaseSystem->Applicatio Management->Application Launch Service',
                'xlspos': [(80, 4)],
                'datatype': 'STR',
                'model_id': 65,
                'needcheck' : True,
            },
            'model_activity':{
                'xlsname': 'BaseSystem->Applicatio Management->Activity Manager',
                'xlspos': [(81, 4)],
                'datatype': 'STR',
                'model_id': 66,
                'needcheck' : True,
            },
            'model_media':{
                'xlsname': 'Application Service->Multimedia->Media Service',
                'xlspos': [(82, 4)],
                'datatype': 'STR',
                'model_id': 67,
                'needcheck' : True,
            },
            'model_bluetooth_service':{
                'xlsname': 'Application Service->Connectivity->BluetoothService->bluetooth_service',
                'xlspos': [(83, 5)],
                'datatype': 'STR',
                'model_id': 68,
                'needcheck' : True,
            },
            'model_DCM_service':{
                'xlsname': 'Application Service->Connectivity->DCM Service->DCM Service',
                'xlspos': [(84, 5)],
                'datatype': 'STR',
                'model_id': 69,
                'needcheck' : True,
            },
            'model_help_service':{
                'xlsname': 'Application Service->Connectivity->DCM Service->Help Service',
                'xlspos': [(85, 5)],
                'datatype': 'STR',
                'model_id': 70,
                'needcheck' : True,
            },
            'model_cm_service':{
                'xlsname': 'Application Service->Connectivity->Conn Utility Service->Cm Service',
                'xlspos': [(86, 5)],
                'datatype': 'STR',
                'model_id': 71,
                'needcheck' : True,
            },
            'model_cu_service':{
                'xlsname': 'Application Service->Connectivity->Conn Utility Service->Cu Service',
                'xlspos': [(87, 5)],
                'datatype': 'STR',
                'model_id': 72,
                'needcheck' : True,
            },
            'model_sfm_service':{
                'xlsname': 'Application Service->Connectivity->Conn Utility Service->Sfm Service',
                'xlspos': [(88, 5)],
                'datatype': 'STR',
                'model_id': 73,
                'needcheck' : True,
            },
            'model_wlan_controller':{
                'xlsname': 'Application Service->Connectivity->Wireless Lan Controller',
                'xlspos': [(89, 4)],
                'datatype': 'STR',
                'model_id': 74,
                'needcheck' : True,
            },
            'model_wlan_middle_service':{
                'xlsname': 'Application Service->Connectivity->Wlan Middle Service',
                'xlspos': [(90, 4)],
                'datatype': 'STR',
                'model_id': 75,
                'needcheck' : True,
            },
            'model_comarb_service':{
                'xlsname': 'Application Service->Connectivity->Comarb_service',
                'xlspos': [(91, 4)],
                'datatype': 'STR',
                'model_id': 76,
                'needcheck' : True,
            },
            'model_network_manager':{
                'xlsname': 'Application Service->Connectivity->Network Manager',
                'xlspos': [(92, 4)],
                'datatype': 'STR',
                'model_id': 77,
                'needcheck' : True,
            },
            'model_smartphone':{
                'xlsname': 'Application Service->Connectivity->Smartphone Connection Service',
                'xlspos': [(93, 4)],
                'datatype': 'STR',
                'model_id': 78,
                'needcheck' : True,
            },
            'model_fuel':{
                'xlsname': 'Application Service->Vehicle Cooperation->Fuel Consumption',
                'xlspos': [(94, 4)],
                'datatype': 'STR',
                'model_id': 79,
                'needcheck' : True,
            },
            'model_energy':{
                'xlsname': 'Application Service->Vehicle Cooperation->Energy Monitor',
                'xlspos': [(95, 4)],
                'datatype': 'STR',
                'model_id': 80,
                'needcheck' : True,
            },
            'model_seat':{
                'xlsname': 'Application Service->Vehicle Cooperation->Seat',
                'xlspos': [(96, 4)],
                'datatype': 'STR',
                'model_id': 81,
                'needcheck' : True,
            },
            'model_DMS':{
                'xlsname': 'Application Service->Vehicle Cooperation->DMS',
                'xlspos': [(97, 4)],
                'datatype': 'STR',
                'model_id': 82,
                'needcheck' : True,
            },
            'model_aircon':{
                'xlsname': 'Application Service->Vehicle Cooperation->Aircon',
                'xlspos': [(98, 4)],
                'datatype': 'STR',
                'model_id': 83,
                'needcheck' : True,
            },
            'model_camera':{
                'xlsname': 'Application Service->Vehicle Cooperation->Camera',
                'xlspos': [(99, 4)],
                'datatype': 'STR',
                'model_id': 84,
                'needcheck' : True,
            },
            'model_meter':{
                'xlsname': 'Application Service->Vehicle Cooperation->Meter',
                'xlspos': [(100, 4)],
                'datatype': 'STR',
                'model_id': 85,
                'needcheck' : True,
            },
            'model_customize':{
                'xlsname': 'Application Service->Vehicle Cooperation->Customize',
                'xlspos': [(101, 4)],
                'datatype': 'STR',
                'model_id': 86,
                'needcheck' : True,
            },
            'model_diag':{
                'xlsname': 'Application Service->Vehicle Cooperation->Diag',
                'xlspos': [(102, 4)],
                'datatype': 'STR',
                'model_id': 87,
                'needcheck' : True,
            },
            'model_personal':{
                'xlsname': 'Application Service->Setting->Delete Personal Data Service',
                'xlspos': [(103, 4)],
                'datatype': 'STR',
                'model_id': 88,
                'needcheck' : True,
            },
            'model_setting':{
                'xlsname': 'Application Service->Setting->Info Setting Service',
                'xlspos': [(104, 4)],
                'datatype': 'STR',
                'model_id': 89,
                'needcheck' : True,
            },
            'model_menu':{
                'xlsname': 'Application Service->Setting->Menu Service',
                'xlspos': [(105, 4)],
                'datatype': 'STR',
                'model_id': 90,
                'needcheck' : True,
            },
            'model_contents':{
                'xlsname': 'Application Service->Misc->Contents Manager',
                'xlspos': [(106, 4)],
                'datatype': 'STR',
                'model_id': 91,
                'needcheck' : True,
            },
            'model_reprogramming':{
                'xlsname': 'Application Service->Misc->Reprogramming Service',
                'xlspos': [(107, 4)],
                'datatype': 'STR',
                'model_id': 92,
                'needcheck' : True,
            },
            'model_status_publisher':{
                'xlsname': 'Application Service->Misc->StatusPublisher',
                'xlspos': [(108, 4)],
                'datatype': 'STR',
                'model_id': 93,
                'needcheck' : True,
            },
            'model_focus':{
                'xlsname': 'Application Service->Misc->Focus Library',
                'xlspos': [(109, 4)],
                'datatype': 'STR',
                'model_id': 94,
                'needcheck' : True,
            },
            'model_libals':{
                'xlsname': 'Application Service->Misc->Libals',
                'xlspos': [(110, 4)],
                'datatype': 'STR',
                'model_id': 95,
                'needcheck' : True,
            },
            'model_remote_service':{
                'xlsname': 'Application Service->Misc->RemoteService',
                'xlspos': [(111, 4)],
                'datatype': 'STR',
                'model_id': 96,
                'needcheck' : True,
            },
            'model_electronic_OM':{
                'xlsname': 'Application Service->Misc->EOM Service->ElectronicOM',
                'xlspos': [(112, 5)],
                'datatype': 'STR',
                'model_id': 97,
                'needcheck' : True,
            },
            'model_browser':{
                'xlsname': 'Application Service->Misc->EOM Service->Browser',
                'xlspos': [(113, 5)],
                'datatype': 'STR',
                'model_id': 98,
                'needcheck' : True,
            },
            'model_vehicle_info':{
                'xlsname': 'Application Service->Vehicle Information Service->Vehicle Info',
                'xlspos': [(114, 4)],
                'datatype': 'STR',
                'model_id': 99,
                'needcheck' : True,
            },
            'model_main':{
                'xlsname': 'Application Framework->App Main',
                'xlspos': [(115, 4)],
                'datatype': 'STR',
                'model_id': 100,
                'needcheck' : True,
            },
            'model_framework':{
                'xlsname': 'Application Framework->Framework',
                'xlspos': [(116, 4)],
                'datatype': 'STR',
                'model_id': 101,
                'needcheck' : True,
            },
            'model_notify':{
                'xlsname': 'Application Framework->Notify Service',
                'xlspos': [(117, 4)],
                'datatype': 'STR',
                'model_id': 102,
                'needcheck' : True,
            },
            'model_str':{
                'xlsname': 'Application Framework->Str Code',
                'xlspos': [(118, 4)],
                'datatype': 'STR',
                'model_id': 103,
                'needcheck' : True,
            },
            'model_trinity':{
                'xlsname': 'Application Framework->Trinity',
                'xlspos': [(119, 4)],
                'datatype': 'STR',
                'model_id': 104,
                'needcheck' : True,
            },
            'model_utility':{
                'xlsname': 'Application Framework->Utility',
                'xlspos': [(120, 4)],
                'datatype': 'STR',
                'model_id': 105,
                'needcheck' : True,
            },
            'supple_spec':{
                'xlsname': '補足参照仕様書',
                'xlspos': [(121, 1)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'uncheck':{
                'xlsname': '未検証',
                'xlspos': [(122, 1)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'ana_remark':{
                'xlsname': '備考',
                'xlspos': [(123, 1)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'ana_1':{
                'xlsname': '1',
                'xlspos': [(124, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'ana_2': {
                'xlsname': '2',
                'xlspos': [(125, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'ana_3': {
                'xlsname': '3',
                'xlspos': [(126, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'ana_4': {
                'xlsname': '4',
                'xlspos': [(127, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'new_date':{
                'xlsname': '更新日',
                'xlspos': [(128, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'reason':{
                'xlsname': '更新内容',
                'xlspos': [(129, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'asta_filename':{
                'xlsname': 'astaファイル名',
                'xlspos': [(130, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'review_result': {
                'xlsname': 'レビュー結果',
                'xlspos': [(131, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_no': {
                'xlsname': '指摘No.',
                'xlspos': [(132, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_status': {
                'xlsname': 'ステータス',
                'xlspos': [(133, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_comment': {
                'xlsname': 'コメント',
                'xlspos': [(134, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'reader_check': {
                'xlsname': 'リーダチェック',
                'xlspos': [(135, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'reader2_check': {
                'xlsname': 'リーダ２チェック',
                'xlspos': [(136, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'final_check': {
                'xlsname': '最終チェック',
                'xlspos': [(137, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_charger': {
                'xlsname': '担当',
                'xlspos': [(138, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_priority': {
                'xlsname': '優先度',
                'xlspos': [(139, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'pointout_date': {
                'xlsname': '指摘提出日',
                'xlspos': [(140, 5)],
                'datatype': 'DATETIME',
                'needcheck': True,
            },
            'suntec_status': {
                'xlsname': 'Suntecステータス',
                'xlspos': [(141, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'fixed': {
                'xlsname': '修正済み',
                'xlspos': [(142, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'suntec_remark': {
                'xlsname': 'Suntec備考',
                'xlspos': [(143, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'arl_rel': {
                'xlsname': 'ARL関連指摘',
                'xlspos': [(144, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'suntec_cannot_modify': {
                'xlsname': 'Suntec修正不可',
                'xlspos': [(145, 5)],
                'datatype': 'STR',
                'needcheck': True,
            },
            'lock_status': {
                'xlsname': '',
                'xlspos': [(146, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
            'group_name': {
                'xlsname': '',
                'xlspos': [(147, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
            'ana_md5': {
                'xlsname': '',
                'xlspos': [(148, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
            'job_status': {
                'xlsname': '',
                'xlspos': [(149, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
        }

        self.xls_sheet_name = 'TAGL要件分析'
        self.start_data_row = 6
        self.id_col = "definition_id"