# -*- coding: UTF-8 -*-

class DefV011():
    def __init__(self):
        self.doc_type = 'DEF'
        self.version = '0.11'
        self.doc_format_dict = {
            'author_name':{
                'xlsname':'担当',
                'xlspos':[(1,5)],
                'datatype' : 'STR',
                'needcheck' : True,
            },
            'hu_def_id':{
                'xlsname':'H/U要件定義ID',
                'xlspos':[(2,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'definition_id':{
                'xlsname':'TAGL要件定義ID',
                'xlspos':[(3,5)],
                'datatype': 'FORMULAR_DEFID',
                'needcheck' : True,
            },
            'unique_id':{
                'xlsname': 'ユニークID',
                'xlspos': [(4,5)],
                'datatype': 'INT',
                'needcheck' : True,
            },
            'major_category':{
                'xlsname': 'H/U要件定義書から転記->大分類',
                'xlspos': [(5,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },

            'medium_category':{
                'xlsname': 'H/U要件定義書から転記->中分類',
                'xlspos': [(6,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'small_category':{
                'xlsname': 'H/U要件定義書から転記->小分類',
                'xlspos': [(7,5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'detail':{
                'xlsname': 'H/U要件定義書から転記->詳細',
                'xlspos': [(8, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'basic_req':{
                'xlsname': 'H/U要件定義書から転記->基本要件',
                'xlspos': [(9, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'rel_requirement':{
                'xlsname': 'ARLから転記->ARL要件->関連基本要件',
                'xlspos': [(10, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'exception':{
                'xlsname': '除外',
                'xlspos': [(11, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'dcu_status':{
                'xlsname': 'H/U要件定義書から転記->DCU->状態',
                'xlspos': [(12, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'dcu_trigger':{
                'xlsname': 'H/U要件定義書から転記->DCU->トリガー',
                'xlspos': [(13, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'dcu_action':{
                'xlsname': 'H/U要件定義書から転記->DCU->動作',
                'xlspos': [(14, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'meu_status':{
                'xlsname': 'H/U要件定義書から転記->MEU->状態',
                'xlspos': [(15, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'meu_trigger':{
                'xlsname': 'H/U要件定義書から転記->MEU->トリガー',
                'xlspos': [(16, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'meu_action':{
                'xlsname': 'H/U要件定義書から転記->MEU->動作',
                'xlspos': [(17, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'hu_remark':{
                'xlsname': 'H/U要件定義書から転記->備考(HU要件定義)',
                'xlspos': [(18, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'dcu_meu':{
                'xlsname': 'DCU/MEUどちらの想定か',
                'xlspos': [(19, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_status':{
                'xlsname': '責務分担->TAGL-PF->状態',
                'xlspos': [(20, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_trigger':{
                'xlsname': '責務分担->TAGL-PF->トリガー',
                'xlspos': [(21, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'pf_action':{
                'xlsname': '責務分担->TAGL-PF->動作',
                'xlspos': [(22, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'model_power_manage':{
                'xlsname': '責務分担->抽象デバイス->電源管理デバイス',
                'xlspos': [(23, 5)],
                'datatype': 'STR',
                'model_id': 1,
                'needcheck' : True,
            },
            'model_avclan':{
                'xlsname': '責務分担->抽象デバイス->AVCLAN制御デバイス',
                'xlspos': [(24, 5)],
                'datatype': 'STR',
                'model_id': 2,
                'needcheck' : True,
            },
            'model_most':{
                'xlsname': '責務分担->抽象デバイス->MOST制御デバイス',
                'xlspos': [(25, 5)],
                'datatype': 'STR',
                'model_id': 3,
                'needcheck' : True,
            },
            'model_can':{
                'xlsname': '責務分担->抽象デバイス->CAN制御デバイス',
                'xlspos': [(26, 5)],
                'datatype': 'STR',
                'model_id': 4,
                'needcheck' : True,
            },
            'model_ig':{
                'xlsname': '責務分担->抽象デバイス->ジカ線入力デバイス',
                'xlspos': [(27, 5)],
                'datatype': 'STR',
                'model_id': 5,
                'needcheck' : True,
            },
            'model_save_memory':{
                'xlsname': '責務分担->抽象デバイス->不揮発メモリデバイス',
                'xlspos': [(28, 5)],
                'datatype': 'STR',
                'model_id': 6,
                'needcheck' : True,
            },
            'model_voice_out':{
                'xlsname': '責務分担->抽象デバイス->音声出力デバイス',
                'xlspos': [(29, 5)],
                'datatype': 'STR',
                'model_id': 7,
                'needcheck' : True,
            },
            'model_voice_in':{
                'xlsname': '責務分担->抽象デバイス->音声入力セレクタデバイス',
                'xlspos': [(30, 5)],
                'datatype': 'STR',
                'model_id': 8,
                'needcheck' : True,
            },
           'model_bt':{
                'xlsname': '責務分担->抽象デバイス->BTデバイス',
                'xlspos': [(31, 5)],
                'datatype': 'STR',
               'model_id': 9,
                'needcheck' : True,
            },
            'model_wifi':{
                'xlsname': '責務分担->抽象デバイス->WIFIデバイス',
                'xlspos': [(32, 5)],
                'datatype': 'STR',
                'model_id': 10,
                'needcheck' : True,
            },
            'model_touchpanel':{
                'xlsname': '責務分担->抽象デバイス->タッチパネル制御デバイス',
                'xlspos': [(33, 5)],
                'datatype': 'STR',
                'model_id': 11,
                'needcheck' : True,
            },
            'model_touchpad':{
                'xlsname': '責務分担->抽象デバイス->タッチパッド制御デバイス',
                'xlspos': [(34, 5)],
                'datatype': 'STR',
                'model_id': 12,
                'needcheck' : True,
            },
            'model_rotery_switch':{
                'xlsname': '責務分担->抽象デバイス->ロータリースイッチ、キースイッチ検出デバイス',
                'xlspos': [(35, 5)],
                'datatype': 'STR',
                'model_id': 13,
                'needcheck' : True,
            },
            'model_gps':{
                'xlsname': '責務分担->抽象デバイス->GPSデバイス',
                'xlspos': [(36, 5)],
                'datatype': 'STR',
                'model_id': 14,
                'needcheck' : True,
            },
            'model_radio':{
                'xlsname': '責務分担->抽象デバイス->Radioチューナーデバイス（XM、DAB含む）',
                'xlspos': [(37, 5)],
                'datatype': 'STR',
                'model_id': 15,
                'needcheck' : True,
            },
            'model_tuner':{
                'xlsname': '責務分担->抽象デバイス->地デジチューナーデバイス',
                'xlspos': [(38, 5)],
                'datatype': 'STR',
                'model_id': 16,
                'needcheck' : True,
            },
            'model_security_chip':{
                'xlsname': '責務分担->抽象デバイス->セキュリティチップデバイス',
                'xlspos': [(39, 5)],
                'datatype': 'STR',
                'model_id': 17,
                'needcheck' : True,
            },
            'model_mic_adc':{
                'xlsname': '責務分担->抽象デバイス->マイク用ADCデバイス',
                'xlspos': [(40, 5)],
                'datatype': 'STR',
                'model_id': 18,
                'needcheck' : True,
            },
            'model_dvd':{
                'xlsname': '責務分担->抽象デバイス->DVD映像デコーダデバイス',
                'xlspos': [(41, 5)],
                'datatype': 'STR',
                'model_id': 19,
                'needcheck' : True,
            },
            'model_video_in':{
                'xlsname': '責務分担->抽象デバイス->映像信号入力セレクタデバイス',
                'xlspos': [(42, 5)],
                'datatype': 'STR',
                'model_id': 20,
                'needcheck' : True,
            },
            'model_video_out':{
                'xlsname': '責務分担->抽象デバイス->映像信号出力デバイス(DCU→各ディスプレイ/ MEU→DCU)',
                'xlspos': [(43, 5)],
                'datatype': 'STR',
                'model_id': 21,
                'needcheck' : True,
            },
            'model_cd_dvd_bd':{
                'xlsname': '責務分担->抽象デバイス->CD/DVD/BD制御デバイス',
                'xlspos': [(44, 5)],
                'datatype': 'STR',
                'model_id': 22,
                'needcheck' : True,
            },
            'model_ecnc':{
                'xlsname': '責務分担->抽象デバイス->ECNCデバイス',
                'xlspos': [(45, 5)],
                'datatype': 'STR',
                'model_id': 23,
                'needcheck' : True,
            },
            'model_usb':{
                'xlsname': '責務分担->抽象デバイス->USB2.0-Host/Functionデバイス',
                'xlspos': [(46, 5)],
                'datatype': 'STR',
                'model_id': 24,
                'needcheck' : True,
            },
            'model_apple_assure':{
                'xlsname': '責務分担->抽象デバイス->APPLE認証デバイス',
                'xlspos': [(47, 5)],
                'datatype': 'STR',
                'model_id': 25,
                'needcheck' : True,
            },
			'model_rtc':{
                'xlsname': '責務分担->抽象デバイス->RTCデバイス',
                'xlspos': [(48, 5)],
                'datatype': 'STR',
                'model_id': 26,
                'needcheck' : True,
            },
            'model_usbroll_switch':{
                'xlsname': '責務分担->抽象デバイス->USBロールスイッチ',
                'xlspos': [(49, 5)],
                'datatype': 'STR',
                'model_id': 27,
                'needcheck' : True,
            },
            'model_temperature':{
                'xlsname': '責務分担->抽象デバイス->温度検知デバイス',
                'xlspos': [(50, 5)],
                'datatype': 'STR',
                'model_id': 28,
                'needcheck' : True,
            },
            'model_sdslot':{
                'xlsname': '責務分担->抽象デバイス->SDスロットデバイス',
                'xlspos': [(51, 5)],
                'datatype': 'STR',
                'model_id': 29,
                'needcheck' : True,
            },
            'def_remark':{
                'xlsname': '備考',
                'xlspos': [(52, 4)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'notice':{
                'xlsname': '責務分担の特記事項',
                'xlspos': [(53, 4)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'rel_flow_diagram':{
                'xlsname': '参考文献->参考ウォークスルー図',
                'xlspos': [(54, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'rel_hal_design':{
                'xlsname': '参考文献->参考HAL設計書',
                'xlspos': [(55, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'other_spec':{
                'xlsname': '参考文献->その他仕様（リファハード仕様等）',
                'xlspos': [(56, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'implementation':{
                'xlsname': 'リファレンスハード上での実現可否',
                'xlspos': [(57, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'analysis':{
                'xlsname': '詳細分析可否',
                'xlspos': [(58, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'unrequire':{
                'xlsname': '未要件分析',
                'xlspos': [(59, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            'new_date':{
                'xlsname': '日付',
                'xlspos': [(60, 5)],
                'datatype': 'DATETIME',
                'needcheck' : True,
            },
            'reason':{
                'xlsname': '変更理由',
                'xlspos': [(61, 5)],
                'datatype': 'STR',
                'needcheck' : True,
            },
            # 'review_result':{
            #     'xlsname': 'レビュー結果',
            #     'xlspos': [(64, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_no':{
            #     'xlsname': '指摘No.',
            #     'xlspos': [(65, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_status':{
            #     'xlsname': 'ステータス',
            #     'xlspos': [(66, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_comment':{
            #     'xlsname': 'コメント',
            #     'xlspos': [(67, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'reader_check':{
            #     'xlsname': 'リーダチェック',
            #     'xlspos': [(68, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'reader2_check':{
            #     'xlsname': 'リーダ２チェック',
            #     'xlspos': [(69, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'final_check':{
            #     'xlsname': '最終チェック',
            #     'xlspos': [(70, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_charger':{
            #     'xlsname': '担当',
            #     'xlspos': [(71, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_priority':{
            #     'xlsname': '優先度',
            #     'xlspos': [(72, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'pointout_date':{
            #     'xlsname': '指摘提出日',
            #     'xlspos': [(73, 5)],
            #     'datatype': 'DATETIME',
            #     'needcheck': True,
            # },
            # 'fixed':{
            #     'xlsname': '修正済み',
            #     'xlspos': [(74, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            # 'suntec_remark':{
            #     'xlsname': 'Suntec備考',
            #     'xlspos': [(75, 5)],
            #     'datatype': 'STR',
            #     'needcheck': True,
            # },
            'lock_status': {
                'xlsname': '',
                'xlspos': [(62, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
            'group_name': {
                'xlsname': '',
                'xlspos': [(63, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
            'def_md5': {
                'xlsname': '',
                'xlspos': [(64, 5)],
                'datatype': 'STR',
                'needcheck': False,
            },
        }

        self.xls_sheet_name = 'TAGL要件定義'
        self.start_data_row = 6
        self.id_col = "definition_id"